### ISSUE TITLE
ROADMAP 1.0

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/unite-cms#351]
unite cms is getting more and more stable and we have already implemented much of our internal roadmap. However, we want to discuss our roadmap with all of you and want to invite you to suggest and upvote any features. 

## Must be implemented until v1.0
- [x] Grid view #349 
- [ ] Translations GraphQL API refactoring #347 
- [ ] Improved Docs on website
- [ ] Roadmap voting tool on website
- [ ] More console commands #292 
- [ ] Finer permission management #252 
- [ ] Tree sort functionality #231 
- [ ] Opt-in for registration #155 
- [ ] Log errors and events and show it to org / domain admin #154 
- [ ] Allow to manage domain member revisions #67 
- [ ] API delete / restore / delete definitely actions #4 
- [ ] API content / setting revert actions #3

## Should be implemented until v1.0
- [ ] Git integration for domain config files updates #340 
- [ ] Description, initial_data and required option for all core field types #239 #350 
- [ ] UI Refactoring of domain changes validation step #341 
- [ ] Captcha field #313 
- [ ] FIlter nested collection fields #296 
- [ ] Field data processor #218 

## Can be implemented until v1.0
- [ ] Sign up with google or any other oauth provider #335 
- [ ] GraphQL API: Allow to filter by referenced content fields #326 
- [ ] Image resize presets #321 
- [ ] Clone content entities #316 
- [ ] Reference field inline edit #238 

## Will be implemented after v1.0

**Comment by Benedict-Lojewski** [comment]
It would be great if we can select multiple rows and delete them at the same time.

**Comment by Clonk-HTML5** [comment]
For me would "FIlter nested collection fields #296" a must be!
What do you think ?
Filtering is very important for a lot of Applications.

**Comment by franzwilding** [comment]
@Clonk-HTML5 Yes I also think is a very important feature! Lets test it out with the mysql8 function I mentioned in #298 and implement it if this is working out!

**Comment by franzwilding** [comment]
> It would be great if we can select multiple rows and delete them at the same time.

Hey @Benedict-Lojewski! Do we have any other batch-able actions like "delete"? Maybe also "restore" and "delete definitely". Are there any others?

I could also imagine that this is a good feature for version 1.0.*, because it does not include any API changes.

**Comment by stefan-kamsker** [comment]
from the left over ones, i'm for
**Must be implemented until v1.0**
- Tree sort functionality
**Should be implemented until v1.0**
- Reverse References Field Type
- Field data processor

**Comment by TomDeSmet** [comment]
#4 would be my most important request. Being able to delete entries is a must for any CMS!

**Comment by franzwilding** [comment]
> #4 would be my most important request. Being able to delete entries is a must for any CMS!

I split the issue into two issues. We will implement delete in release 0.7.3. Thanks for your feedback

**Comment by franzwilding** [comment]
> For me would "FIlter nested collection fields #296" a must be!
> What do you think ?
> Filtering is very important for a lot of Applications.

Please take a look at my comment in #296.

**Comment by Clonk-HTML5** [comment]
@franzwilding 
so thank you this is working at the moment so there would be no Problem to move the issue to the post 1.0 version.

At my current Step this Issue: #326 would be great but maybe not a must have.
GraphQL API: Allow to filter by referenced content fields #326

**Comment by franzwilding** [comment]
@Clonk-HTML5 
> At my current Step this Issue: #326 would be great but maybe not a must have.
> GraphQL API: Allow to filter by referenced content fields #326

I would also like to have this feature and because it does not change any API, someone could just implement it. It should be possible by detecting references, adding SQL Joins and modify the left hand of the comparison from ref_field.subfield.x to c2.subfield.x where c2 is the named joined table. 

Anyone here, who could implement this?

**Comment by dynamiccontent** [comment]
I would really like to use your project but you really need to update your documentation and tutorials. It really hurts when you cannot even test your project because documentation/examples are not up to date.
I have been trying to setup https://medium.com/unite-cms/create-a-blog-using-unite-cms-vue-js-2784743bb488 so I can see how it works but I keep getting
contentTypes[articles].views[all].settings: The child node "columns" at path "settings" is deprecated.
What is the solution for this?
I am using unite cms 0.9.1. Should I downgrade to unite cms v0.8.0 so I will be able to setup this example?
Documentation is one of the most important parts of a project so people can test it properly and give you feedback.

**Comment by franzwilding** [comment]
Hey! You are right and I am sorry! We are at the moment on the finish line of v0.10.0 and will do a complete rewrite of the docs in the next weeks. 

For your problem: please have a look at the docs at the section for table views. You will see a good example of how to configure views there
